
export const LOGIN_REQUEST = 'LOGIN_REQUEST'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'


export const SIGN_OUT_REQUEST = 'SIGN_OUT_REQUEST'; export const SIGN_OUT_ERROR = 'SIGN_OUT_ERROR'; export const SIGN_OUT_SUCCESS ='SIGN_OUT_SUCCESS'

export const CATEGORY_FETCH = 'CATEGORY_FETCH';

export const FETCH_SUCCESS = 'FETCH_SUCCESS';

export const FETCH_ERROR = 'FETCH_ERROR';

export const ADD_CATEGORY_REQUEST = 'ADD_CATEGORY_REQUEST'

export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS'

export const ADD_CATEGORY_ERROR = 'ADD_CATEGORY_ERROR'

export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS'

export const  FETCH_BY_SLUG = 'FETCH_BY_SLUG';


export const DISPLAY_BY_TYPE_REQUEST = 'DISPLAY_BY_TYPE_REQUEST';

export const DISPLAY_BY_TYPE_SUCCESS = 'DISPLAY_BY_TYPE_SUCCESS'


export const GET_PRODUCT_BY_ID_REQUEST = 'GET_PRODUCT_BY_ID_REQUEST';

export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS';


export const cartConstants = {
    ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
    ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
    ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",
    RESET_CART: "RESET_CART",
  
    REMOVE_CART_ITEM_REQUEST: "REMOVE_CART_ITEM_REQUEST",
    REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
    REMOVE_CART_ITEM_FAILURE: "REMOVE_CART_ITEM_FAILURE",
  };

  export const userConstants = {
    GET_USER_ADDRESS_REQUEST: "GET_USER_ADDRESS_REQUEST",
    GET_USER_ADDRESS_SUCCESS: "GET_USER_ADDRESS_SUCCESS",
    GET_USER_ADDRESS_FAILURE: "GET_USER_ADDRESS_FAILURE",
    ADD_USER_ADDRESS_REQUEST: "ADD_USER_ADDRESS_REQUEST",
    ADD_USER_ADDRESS_SUCCESS: "ADD_USER_ADDRESS_SUCCESS",
    ADD_USER_ADDRESS_FAILURE: "ADD_USER_ADDRESS_FAILURE",
    ADD_USER_ORDER_REQUEST: "ADD_USER_ORDER_REQUEST",
    ADD_USER_ORDER_SUCCESS: "ADD_USER_ORDER_SUCCESS",
    ADD_USER_ORDER_FAILURE: "ADD_USER_ORDER_FAILURE",
  
    GET_USER_ORDER_REQUEST: "GET_USER_ORDER_REQUEST",
    GET_USER_ORDER_SUCCESS: "GET_USER_ORDER_SUCCESS",
    GET_USER_ORDER_FAILURE: "GET_USER_ORDER_FAILURE",
  
    GET_USER_ORDER_DETAILS_REQUEST: "GET_USER_ORDER_DETAILS_REQUEST",
    GET_USER_ORDER_DETAILS_SUCCESS: "GET_USER_ORDER_DETAILS_SUCCESS",
    GET_USER_ORDER_DETAILS_FAILURE: "GET_USER_ORDER_DETAILS_FAILURE",
  };